name: Release

on:
  push:
    branches:
      - main

jobs:
  test-check-lint:
    uses: ./.github/workflows/test-check-lint.yml

  release:
    name: Build Publish Crate - Linux-x86_64
    runs-on: ubuntu-latest
    needs: [test-check-lint]
    environment: deploy #!! DO NOT CHANGE THIS LINE !! #
    container:
      image: rust:1.76
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - run: git config --global --add safe.directory $(realpath .)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install zip
        run: apt-get update && apt-get install -y zip

      - name: Semantic Release
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
