name: Test-Check-Lint

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Test the release
    runs-on: ubuntu-latest
        container:
      image: rust:1.76
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install zip
        run: |
          apt-get update
          apt-get install -y zip
        user: root
      - name: Semantic Release
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

